"""Deterministic FastAPI server for fullstack Playwright E2E testing.

Runs an isolated FastAPI app instance with deterministic mock bundles wired to the
real production pipeline on an isolated test port (default 18082).
Allows test port 13002 via CORS strictly on this test app instance.
"""
import os
import sys
import asyncio
from datetime import date
from decimal import Decimal
from pathlib import Path

# Ensure backend directory is in sys.path
backend_dir = Path(__file__).resolve().parent.parent.parent
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import app.main as main_module
from app.config import DEFAULT_ASSUMPTIONS
from tests.fixtures.mock_bundles import get_mock_bundle_for_ticker
from app.providers.yfinance_provider import YFinanceProvider
from app.services.valuation_service import FinancialDataService, MemoryTTLCache, ValuationService
from app.models.overrides import ValuationOverrideRequest


class E2EFixtureYFinanceProvider(YFinanceProvider):
    """Production provider with explicit FY FCFF only for browser fixtures.

    The regular mock bundles intentionally exercise the production missing-
    FCFF gate.  This isolated browser provider supplies auditable, full-FY
    analyst estimates so the workflow can verify DCF overrides/reset/export;
    production eligibility code remains unchanged.
    """

    def get_cash_flow(self, ticker: str, budget=None):
        data = dict(super().get_cash_flow(ticker, budget=budget))
        # Driver-override workflow needs a complete operating bridge. These
        # are explicit fixture inputs, not a production fallback or synthetic
        # value generated by the live provider.
        data.update({
            "da": Decimal("50000000"),
            "da_period": "TTM",
            "da_as_of": date(2026, 9, 10),
            "da_is_fallback": False,
            "nwc_change": Decimal("10000000"),
        })
        return data

    def get_forward_estimates(self, ticker: str, budget=None):
        data = dict(super().get_forward_estimates(ticker, budget=budget))
        data.update({
            "forward_fcff_1y": Decimal("560000000"),
            "forward_fcff_1y_source_type": "analyst_estimate",
            "forward_fcff_1y_period": "FY2026E",
            "forward_fcff_1y_as_of": date(2026, 9, 10),
            "forward_fcff_1y_source": "Deterministic E2E analyst FCFF fixture",
            "forward_fcff_1y_notes": "Explicit full fiscal-year FCFF; test-only fixture input.",
            "forward_fcff_2y": Decimal("784000000"),
            "forward_fcff_2y_source_type": "analyst_estimate",
            "forward_fcff_2y_period": "FY2027E",
            "forward_fcff_2y_as_of": date(2026, 9, 10),
            "forward_fcff_2y_source": "Deterministic E2E analyst FCFF fixture",
            "forward_fcff_2y_notes": "Explicit full fiscal-year FCFF; test-only fixture input.",
        })
        return data


# Use an isolated service graph in the fixture process.  The fixture routes
# below call this graph directly; do not monkeypatch ``app.main`` at import
# time because pytest also imports this module while collecting backend tests.
_fixture_provider = E2EFixtureYFinanceProvider()
_fixture_provider._get_bundle = get_mock_bundle_for_ticker
_fixture_data_service = FinancialDataService(
    provider=_fixture_provider,
    cache=MemoryTTLCache(),
    default_assumptions=DEFAULT_ASSUMPTIONS,
)
_fixture_valuation_service = ValuationService(
    _fixture_data_service,
    default_assumptions=DEFAULT_ASSUMPTIONS,
)


def _resolve_fixture_data_service(provider_override=None):
    if provider_override and provider_override.lower() == "demo":
        return main_module._demo_data_service
    return _fixture_data_service


def _resolve_fixture_valuation_service(provider_override=None):
    if provider_override and provider_override.lower() == "demo":
        return main_module._demo_valuation_service
    return _fixture_valuation_service

# Create dedicated test FastAPI app.  The endpoint bodies mirror production
# handlers but resolve the fixture graph locally, leaving the production app's
# resolver functions untouched for ordinary backend tests.
app = FastAPI(
    title="E2E Test Valuation API",
    description="Isolated test instance for fullstack browser verification",
    version="0.2.0-test",
)

# Configure CORS strictly on this test app instance to permit isolated frontend port 13002
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:13002",
        "http://127.0.0.1:13002",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
async def fixture_health() -> dict[str, object]:
    return {
        "status": "ok",
        "service": "US Stock Valuation API",
        "version": "0.2.0-test",
        "demo_tickers": ["AVGO"],
    }


@app.get("/api/v1/company/{ticker}/snapshot")
async def fixture_get_snapshot(ticker: str, provider: str | None = None):
    try:
        svc = _resolve_fixture_data_service(provider)
        snapshot = await asyncio.to_thread(svc.get_snapshot, ticker)
        return main_module._json_response(snapshot.model_dump(mode="json"))
    except Exception as exc:
        main_module._raise_http(exc)
        raise AssertionError("unreachable")


@app.get("/api/v1/valuation/{ticker}")
async def fixture_get_valuation(ticker: str, provider: str | None = None):
    try:
        svc = _resolve_fixture_valuation_service(provider)
        response = await asyncio.to_thread(svc.compute, ticker)
        return main_module._json_response(main_module._enrich(response.model_dump(mode="json")))
    except Exception as exc:
        main_module._raise_http(exc)
        raise AssertionError("unreachable")


@app.post("/api/v1/valuation/{ticker}")
async def fixture_post_valuation(
    ticker: str,
    body: ValuationOverrideRequest,
    provider: str | None = None,
):
    try:
        svc = _resolve_fixture_valuation_service(provider)
        response = await asyncio.to_thread(svc.compute, ticker, overrides=body.to_override_dict())
        return main_module._json_response(main_module._enrich(response.model_dump(mode="json")))
    except Exception as exc:
        main_module._raise_http(exc)
        raise AssertionError("unreachable")


@app.get("/api/v1/valuation/{ticker}/reset")
async def fixture_reset_valuation(ticker: str, provider: str | None = None):
    try:
        svc = _resolve_fixture_valuation_service(provider)
        response = await asyncio.to_thread(svc.compute, ticker, bypass_cache=True)
        return main_module._json_response(main_module._enrich(response.model_dump(mode="json")))
    except Exception as exc:
        main_module._raise_http(exc)
        raise AssertionError("unreachable")


@app.get("/e2e/health")
def e2e_health() -> dict[str, object]:
    return {
        "status": "ok",
        "service": "deterministic-e2e-fixture",
        "port": int(os.getenv("PORT", "18082")),
        "scenarios": ["growth", "annual_fallback", "conflict"],
    }


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", "18082"))
    uvicorn.run(app, host="127.0.0.1", port=port)
